server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_hotel
    username: postgres
    password: Tanver@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: HOTEL-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
